### ISSUE TITLE
Packaging issue with Python 3 on Fedora

### ISSUE THREAD

**Issue by bochecha** [berdario/pew#102]
I'm trying to package Pew for Fedora.

I have [a repository with work-in-progress packages](https://copr.fedorainfracloud.org/coprs/bochecha/pew/), however one thing is problematic.

I've chosen to build Pew for Python 3, because at this point I'd rather not do anything related to Python 2 if I don't have to. :wink:

So I built Pew and its dependencies as Python 3 modules, and overall everything is working fine... except one tiny little detail.

``` python
    try:
        check_call(["virtualenv", envname] + rest, cwd=str(workon_home))
    except (CalledProcessError, KeyboardInterrupt):
        ...
```

The `/usr/bin/virtualenv` command on Fedora is the Python 2 version. For Python 3, the command is `/usr/bin/virtualenv-3.4`.

As a result, even though I've built Pew for Python 3, I still need to add a dependency on the Python 2 version of virtualenv. :disappointed: 

This `virtualenv`/`virtualenv-3.4` issue is Fedora-specific, as far as I know (Debian only ships `/usr/bin/virtualenv` for the Python 3 version it seems), so I'd understand if that's not something you want to work around upstream.

Possible solutions I can think of include:
- If the `virtualenv` command doesn't exist, try `virtualenv-3.4`, or `virtualenv-3.5`, or... Which is clearly not very smart.
- Stop `subprocess`-ing the command, and instead use a Python module (maybe `venv` for Python >= 3.3 ?)
- A downstream, Fedora-only patch. (this would probably be the worst solution, but I figured I'd mention it... let's find something better)
- Building Pew for Python 2 on Fedora

What do you think?

**Comment by berdario** [comment]
Hi, sorry for not replying earlier. I think there has also been a discussion via email, but I'd like to mention a couple of things here:

- I think that the proper solution is to use [Alternatives](https://fedoraproject.org/wiki/Packaging:Alternatives) (see also [an example of how this is used to select a java version](https://ask.fedoraproject.org/en/question/49060/how-to-make-oracle-jdk-and-jre-as-default-java-in-fedora-20/)). This way Pew would depend on a virtual-package/meta-package "virtualenv", and the python2-virtualenv, python3.4-virtualenv python3.5-virtualenv could all of them be providing it. `/usr/bin/virtualenv` would thus be a symlink to the preferred package installed by the user
- I planned to use `venv`, but I think [it might still be a bit premature](https://github.com/berdario/pew/issues/67). Stop subprocess-ing is also something that I considered doing, and back in February I hoped that `virtualenv-rewrite` would be the way forward (so I refrained from doing any change in that direction until the new virtualenv would've been ready, but I don't think that'll really materialize )

Btw, due to how distracted I've been, if you want I can give you commit access to fix some things (like, falling back on `/usr/bin/virtualenv-3.4` or stop `subprocess`-ing) to help your packaging effort, without having me as a blocker, but I understand also if in the meanwhile you might've moved on and started some other effort.

**Comment by berdario** [comment]
PS: I forgot to mention...

there's [another reason](https://github.com/berdario/pew/issues/88#issuecomment-176225513) why I haven't bothere with an alternative to `subprocess`-ing virtualenv

**Comment by bochecha** [comment]
> I think that the proper solution is to use Alternatives (see also an example of how this is used to select a java version).

I know of the `alternatives` framework, we use it quite

**Comment by berdario** [comment]
Good :)

Let me know if you find a resolution.

Anyhow, it should also be possible to have a Python3-pew packaged in Fedora that depends on the Python2-virtualenv package, shouldn't it?

It's not pretty, but it should be a problem that it'll sort itself, as soon as Fedora drops Python2

**Comment by bochecha** [comment]
> Anyhow, it should also be possible to have a Python3-pew packaged in Fedora that depends on the Python2-virtualenv package, shouldn't it?

That is in fact how I "solved" this problem a few weeks ago. :wink:

**Comment by bochecha** [comment]
This was fixed by https://github.com/berdario/pew/commit/999674cdf4e6e82758b4c8e97abf28e1ed5780bd

Thanks @berdario !

**Comment by meshy** [comment]
I think you're right, it looks as though that commit fixed this. I hope you don't mind if I close this issue as a result!
