### ISSUE TITLE
Can't install on Mac OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by andy47** [berdario/pew#103]
When I `pip install pew` on the system Python on my Mac I see an error because it tries to upgrade the system version of setuptools. There is an error uninstalling the current version of setuptools (1.1.6) because there is a later version noted as a dependency in the pew setup.py. I'm glad that it fails because I don't want to break the system Python install. I'm sad that it fails though because I can't seem to install pew.
Does anyone know of a way of installing pew on Mac OSX that avoids this problem? Fair notice for any proposed answers - I won't run homebrew on my machines.

**Comment by andy47** [comment]
I note that this has come up before on #71 and #83 but I'm either not picking up those fixes or there is another problem introduced by the update to OSX 10.11.3 that I'm running.

**Comment by andy47** [comment]
I'm still struggling with this. On #71 it's stated that this install problem is fixed on OSX and other tickets refer to that one. I still can't install on OSX because the requirements.txt still states `setuptools>=17.1` but my system Python has setuptools 1.1.6 and that can't be updated.

**Comment by andy47** [comment]
For the time being I 'fixed' my system by installing version 0.1.16 of pew. That version doesn't try to upgrade setuptools and works on my Mac running OSX 10.11.3

**Comment by berdario** [comment]
Sorry for not replying earlier, I'm trying to go back and clean a few issues now.

Unfortunately, I don't use Macos and when I wrote [this](https://github.com/berdario/pew/issues/83#issuecomment-174313966) I'm afraid I might've confused the general problem with the Mac-specific issue (since a few people mentioned that they sorted it out, I thought there might've been a way to update setuptools).

I'm afraid that the only true solution is to be able to upgrade Setuptools, and Macos' System Integrity Protection makes it impossible/impractical to upgrade Setuptoos system-wide.

Usually I try to install as much stuff as possible via [Nix](nixos.org/nix) (which works also on Macos, and there's an old nix package for pew, but unfortunately I haven't kept it up-to-date)... for graphical Python software instead (unless I'm on a pure Nixos system) I rely on pipsi, as [suggested in this other comment](https://github.com/berdario/pew/issues/71#issuecomment-160986866).

I'll now push an updated README in which I suggest people to use pipsi, rather than plain pip. I'm afraid that I cannot do much else besides that.
