### ISSUE TITLE
Nice project but.

### ISSUE THREAD

**Issue by AraHaan** [berdario/pew#120]
How can I use this on windows to force my python script to bytecode (while in windows) the files to bytecode the pyc using the linux pyc file magic as it seems they are diferent than the windows 3.5.2. (Yes I need to generate a zip archive with pyc files inside that works on linux as for some unbenowned reason the magic is different.)

**Comment by berdario** [comment]
I think this is out of scope for pew.

You might want to take a [wheel, and compile its files to .pyc](https://bitbucket.org/pypa/wheel/issues/123/wheels-with-no-python-source-only-byte)

Or maybe use [Pex](https://github.com/pantsbuild/pex)

Or maybe [pyinstaller](http://www.pyinstaller.org/)

Afaik Python bytecode should work the same for the same Python version (even if on Linux vs Windows), if you found otherwise can created a reduced test case I'm sure that would be interesting for others (maybe the Python core developers themselves)... but I don't see how pew could help you solve that problem
