### ISSUE TITLE
Add option to run a command in the newly activated env on workon

### ISSUE THREAD

**Issue by sametmax** [berdario/pew#121]
Sometime I want to activate an env, and run a server or something. It would be nice to be able to do:

`pew workon env -e './manage.py runserv'`

Espacially to custom shell profiles.

**Comment by berdario** [comment]
I think what you want is

`pew in env ./manage.py runserv`

**Comment by berdario** [comment]
Or maybe you want the command to be run in the background?
In that case, the never-implemented/merged hook system would be solution

**Comment by sametmax** [comment]
No "in" can't work, because it doesn't activate the env, meaning once the command is done running, you are out of the env. Another problem with in is that it doesn't move to the project directory of the env, so command like ./manage.py will not work since they require you to in the proper directory for the relative path to be valid.

**Comment by berdario** [comment]
> Another problem with in is that it doesn't move to the project directory of the env, so command like ./manage.py will not work since they require you to in the proper directory for the relative path to be valid.

I see, there's no reason this should be the case... this is more of a bug fix, and I'll track this [here](https://github.com/berdario/pew/issues/123)

About allowing commands to run remotely, I could merge a PR for it, but I'm not sure if this should be implemented as hooks, or differently (I never truly felt the need for hooks, so that's why I've been hesitant to implement a similar functionality)
