### ISSUE TITLE
Unable to find bash

### ISSUE THREAD

**Issue by Vayel** [berdario/pew#125]
I cannot work on an env on CentOS Linux 7 (Core):

```
$ pip install --user pew
$ PATH=PATH:~/.local/bin
$ export PATH
$ pew new test
Using base prefix '/usr'
New python executable in /user/7/.base/lefoulov/home/.local/share/virtualenvs/test/bin/python3.5
Not overwriting existing python script /user/7/.base/lefoulov/home/.local/share/virtualenvs/test/bin/python (you must use /user/7/.base/lefoulov/home/.local/share/virtualenvs/test/bin/python3.5)
Installing setuptools, pip, wheel...done.
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
Unable to find bash
$ pew ls
test
$ pew workon test
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
Unable to find bash
$ bash
bash: bash: command not found...
```

Do you need bash to run pew on Linux?

**Comment by berdario** [comment]
No, but what is it that you want to accomplish?

`pew` will fork the `$SHELL` selected by the user, which means that it has to be able to resolve the executable name to its path

if `bash` is not inside `PATH` it won't be able to do that... if you have another shell (e.g. `fish`) inside `~/.local/bin`, as long as `SHELL` is set to `fish`, it'll work

You probably meant

    PATH=$PATH:~/.local/bin

instead of

    PATH=PATH:~/.local/bin

**Comment by Vayel** [comment]
Oh sorry, you're right. That's the same problem as #124, due to user installation.

Thanks.
