### ISSUE TITLE
Which pythonz does pew use?

### ISSUE THREAD

**Issue by nateprewitt** [berdario/pew#134]
pew seems to be unable to install via `pip`/`setuptools` on Python 2.6 because the dependency `pythonz` has an incompatible setup.py. It uses the format function without specifying parameter order inside the curly brackets (e.g. `{0} {1}`) which wasn't supported until 2.7.

I'm happy to submit a PR to fix this but wanted to know where the current repository is. It looks like you maintain a fork which is what the PyPI page points to. However, it doesn't appear to have had a release in a while, the original has recently been updated but isn't compatible with PyPIs infrastructure anymore.

Any comment on which direction to pursue would be greatly appreciated. Thanks!

**Comment by nateprewitt** [comment]
Sorry, I didn't dig deep enough before posting. I've opened berdario/pythonz#1 to address this.

**Comment by berdario** [comment]
Yup, I guess that it might not have been easy to find it, because I kept my code in the `bd` branch... I made that the default branch in Github, so hopefully this shouldn't happen anymore

As you might've seen, unfortunately my idea of pythonz-bd being a shallow fork [didn't pan out](https://github.com/saghul/pythonz/issues/110#issuecomment-183230818)... I haven't had the time to do anything about it, but since I spent quite a bit of time on the changes to pythonz, that it serves its purpose, and that can work even if it's not updated to support the newer python versions (it will just warn about the missing hashes... which btw, the original maintainer is not adding even upstream), I kept it in.

Also, if you and/or @kennethreitz are working on new python tooling, maybe it could be interesting to consider a similar idea to https://github.com/saghul/pythonz/issues/94 ?

**Comment by nateprewitt** [comment]
Thanks so much for the quick response @berdario! I haven't had a chance to glance over that issue yet this morning but I'll take a peek :)
