### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dastagg** [berdario/pew#137]
Running on Arch Linux
pew version       0.1.26
python --version    Python 3.6.1
pip --version    pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)

Whenever I run the workon command, I get an IndexError message:

```
~ ❯❯❯ pew workon
ansible1     crashcourse  flaskr                invent-games  pbytest        pyt_get_started  rpp2-flask-blog         tptjs-06  ttdp            
beginpytest  cs50         flaskwithnewboston    jupyter-blog  pfquickstart   python-guide     rpp2-flask-hello-world  tptjs-08  valencering     
bootcamp     decorators   fsp-deployment-guide  learn_pytest  practi-python  rp1              tpt-jumpstart           tptjs-09  valenceringflask
catinabox    flask        fugue                 lektor        py4fi          rpp1             tptjs-05                tptjs-10  walnotes        
Traceback (most recent call last):
  File "/usr/bin/pew", line 11, in <module>
    load_entry_point('pew==0.1.26', 'console_scripts', 'pew')()
  File "/usr/lib/python3.6/site-packages/pew/pew.py", line 737, in pew
    return command(sys.argv[2:])
  File "/usr/lib/python3.6/site-packages/pew/pew.py", line 351, in workon_cmd
    env = parse_envname(argv, lambda: lsvirtualenv(False))
  File "/usr/lib/python3.6/site-packages/pew/pew.py", line 340, in parse_envname
    env = argv[0]
IndexError: list index out of range
```

It works fine if I: 
* use workon to activate a virtualenv  
* only type just the first few letters and hit tab to autocomplete  
```
~ ❯❯❯ pew workon tptjs-
 -- virtual envs --
tptjs-05  tptjs-06  tptjs-08  tptjs-09  tptjs-10
```

It's just when I use workon by itself to get the list of available virtualenvs that I see the IndexError.

**Comment by anowlcalledjosh** [comment]
This is caused by the assumption in `workon_cmd` that `parse_envname` will always return a valid path. Either `IndexError` should be caught in `pew.workon_cmd` at line 351 of pew/pew.py, or `workon_cmd` needs to check whether `env` is actually a path before continuing (meaning that `parse_envname` can and should return `None` if there is no argument).

Honestly, it seems odd to be passing a callback to `parse_envname` -- the caller should just catch `IndexError` (or check for a `None` return value or whatever) and call it themselves.
