### ISSUE TITLE
Make pythonz optional

### ISSUE THREAD

**Issue by kennethreitz** [berdario/pew#152]
pipenv requires pew, and is very happy with it, but our users have no need for pythonz to be installed.

**Comment by kennethreitz** [comment]
e.g. `$ pip install pew[pythonz]`

**Comment by AlJohri** [comment]
related https://github.com/berdario/pew/issues/146

**Comment by kennethreitz** [comment]
I'd be happy to help maintain this project in order to help make this happen!

**Comment by apatrushev** [comment]
+1. I am using this tool widely because it's workflow more venv oriented than pyenv. Unfortunately the project looks like dead - no new commits, author is not responding to issues/PRs.

**Comment by kennethreitz** [comment]
a fork may be in order!

**Comment by kennethreitz** [comment]
@berdario do you have any thoughts? can you add me as a maintainer?

**Comment by kennethreitz** [comment]
and possibly @nateprewwit and @erinxocon

**Comment by erinxocon** [comment]
Indeed, would be happy to maintain.

**Comment by berdario** [comment]
Added both Kenneth and Erin :)

Thanks a lot for stepping up, and sorry for being really absent lately... I changed jobs once again and that caused Pew to slip a bit further down in my list of things that I had to sort out (also, unlike what I expected, the last few weeks at my previous company hadn't been as slow and easy-going as I expected). I contributed on some other stuff on github, but that was mostly stuff that I worked on when attending hackatons and such.

Every time I saw a github notification about Pew I thought 

> Oh, I should really look into it, but I won't have time now, so I might as well not even read the notification

:/

I'll catch up on the issues a bit now

**Comment by erinxocon** [comment]
@berdario no worries, we've all been there :)

@kennethreitz and I can help, we both use pew with our pipenv tool and think it's great!

**Comment by berdario** [comment]
@erinxocon Thanks a lot for getting this through! :slightly_smiling_face: 

I tagged and released on pypi 0.1.27, if you want to test (it's almost 05.00 here, so I really need to log off)

on the topic of the weird version number: I often thought that I should've committed to version 1.0, but I hesitated to do it, since the idea of implementing some hooks system has been in the air for a long time, and if I'd get around to implementing it just after releasing 1.0, and having to break compatibility for it (forcing a major version bump) I'd hate it...

but maybe I should just swallow the pill?

I really like to see a few other GPG signed commits in the repo :slightly_smiling_face: 
Though I cannot find your public key here, Erin: https://pgp.mit.edu/

Is it available somewhere?

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by Foxboron** [comment]
Thank you, makes this a lot easier to package pew and eventually pipenv for Arch Linux :)

**Comment by erinxocon** [comment]
@berdario I just uploaded my public key, forgot that part :)
