### ISSUE TITLE
pipenv shell spawns CMD.exe instead of powershell when run in powershell

### ISSUE THREAD

**Issue by kimvais** [berdario/pew#183]
The [closed issue in pipenv](https://github.com/pypa/pipenv/issues/915) suggests that this is a bug  in pew

**Comment by berdario** [comment]
Is it possible that with the changes in https://github.com/berdario/pew/pull/177 (sorry, release not out yet) this might not be an issue anymore? (I suspect that pipenv might've called out pew via `cmd` on Windows, which might explain this issue)

@erinxocon do you already know what's the root cause?

I really plan to get the release out ASAP, but work has been busy lately, and family is now visiting... maybe tonight before sleep?

**Comment by techalchemy** [comment]
@berdario @kimvais I have no idea if this is even a problem in pew, but I fixed it in pipenv with this commit: pypa/pipenv@2dc06d4a5cf547833b2faf1fd5f9e72922ce58a8 by calling `pew.workon_cmd` directly instead of using a subprocess call

**Comment by kimvais** [comment]
Ok, seems to be fixed in 11.6 - thanks!
