### ISSUE TITLE
There is no copyright notice in LICENSE

### ISSUE THREAD

**Issue by hroncok** [berdario/pew#190]
The license in LICENSE says:

> **The above copyright notice** and this permission notice shall be included in
> all copies or substantial portions of the Software.

Yet there is no copyright notice at all, thus technically, nobody can follow the license terms. If you want no copyright, consider Public domain or CC0. If you want MIT, please add the copyright notice. It can be:

> Copyright (c) 2013-2018 pew contributors

**Comment by berdario** [comment]
Hi, thanks for the question!

As you might know, thanks to the Berne Convention since 1886, a work doesn't need to be explicitly copyrighted for the copyright to be recognized. This means that even if it's not stated anywhere, the copyright belongs to the same people that would be listed in the notice.

So, rather than saying

> technically, nobody can follow the license terms

I'd rather describe the situation as

> nobody risks screwing up the license by misattributing or improperly modifying the copyright notice

I agree that the MIT license looks poorly worded, but you can think of the copyright notice that it's referring to as the "NULL", "0-length" copyright notice that is already included in the LICENSE file. In light of the above, adding a copyright to "pew contributors" is pretty much tautological and doesn't really add any useful information for anyone.

If you feel that you cannot fork/mirror/redistribute Pew due to the fact that you're afraid that it might be  violating the terms of the license, please take this current message as proof that you (or anyone else) are granted all the rights of the MIT license and can thus redistribute Pew without having to add a copyright notice.

(If you're creating a derivative work, there's nothing that says that you shouldn't adapt the copyright notice however your wish (while still maintaining the attribution correct) so, even if I'd prefer the notice to be omitted for the sake of brevity, there's nothing stopping you from adding it elsewhere)

**Comment by berdario** [comment]
I'll leave the ticket open for now, let me know if the above resolved your issue satisfactorily.

I understand that there's a bit of irony in writing the above ~200 words, rather than adding the 4/5 words of the notice :)

Also, since github.com might disappear, but you might still want to have proof of the above statements independently from it, here are 2 archive links to refer to this discussion:

https://web.archive.org/web/20180412173724/https://github.com/berdario/pew/issues/190

http://archive.is/3q8gu

**Comment by hroncok** [comment]
I think I'm ok with that said. I just assumed it was a mistake not a carefully calculated decision :D

Let's assume the copyright notice is 0-length then and everything is ok.
