### ISSUE TITLE
nix build is failing on Python 3.7

### ISSUE THREAD

**Issue by pfmoore** [berdario/pew#203]
The nix build is failing with an error:

```
/nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux/setup: line 1314: py.test: command not found
builder for '/nix/store/2iylyy9gnk9p53gsb5f954kczfkbpj1j-python3.7-pew.drv' failed with exit code 127
error: build of '/nix/store/2iylyy9gnk9p53gsb5f954kczfkbpj1j-python3.7-pew.drv' failed
The command "nix-build" exited with 100.
```

I know nothing about nix, so if anyone can help with this issue that would be fantastic. It looks as if `py.test` isn't getting installed properly, but I can't see anywhere in the nix script that says what needs to be installed :-(

**Comment by berdario** [comment]
Fixed. 

More than 3 years ago there was only `buildInputs`, nixpkgs in the meanwhile added [`checkInputs`](https://nixos.org/nixpkgs/manual/#build-phase)

Now, build inputs will not be available anymore at test time (this is nice, since it pushes people to separate build and test dependencies, which means that if you don't need to run the tests you won't have to build the test dependencies either.)

Besides that, I added repository pinning, so we won't risk any new unexpected failures in the future, and yet I added a separate configuration that will automatically pick up the latest version of the nixpkgs channel (but that is marked as allowed to fail, so it won't fail the build). I enabled Travis' monthly cron, so we should be able to detect if new Nixpkgs versions will introduce other changes.
