### ISSUE TITLE
pythonz-bd==1.10.2 install problem

### ISSUE THREAD

**Issue by ajschumacher** [berdario/pew#71]
Hi @berdario! No issues on your `pythonz`, so posting here:

```
$ pip install pythonz-bd==1.10.2
Collecting pythonz-bd==1.10.2
  Using cached pythonz-bd-1.10.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in pythonz-bd setup command: Invalid environment marker: python_version>="3.5"
$ pip install pythonz-bd==1.10.1
# success
```

This is on Python 2.7.6. Is that version too old to handle this 3.5 version spec thing maybe? I'm not sure what the problem is.

The 1.10.1 workaround seems like it will work for me, but wanted to let you know in case others encounter this.

**Comment by berdario** [comment]
Have you tried to run `pip install --upgrade pip` ?

**Comment by ajschumacher** [comment]
`pip` is at 7.1.2, which looks like the most recent version, I think.

**Comment by berdario** [comment]
Weird, the latest up-to-date pip should use a recent enough version of setuptools

And with a version of setuptools that includes [this commit](https://bitbucket.org/pypa/setuptools/commits/78584e29a495ee0eb06655fcf82a51f37e6dd73b?at=default), you shouldn't see that problem

I guess that it's possible to have the latest pip with a slightly older setuptools... I'll look into this, but I don't have time today

Thanks for the bug report!

**Comment by ajschumacher** [comment]
Thank you! `pew` :heart:

**Comment by Rafiot** [comment]
For the records, I got this error on debian  jessie.

The fix was to upgrade pip and setuptools (just pip was still giving me the error).

**Comment by kierun** [comment]
Had the same problem and `setuptools` was the problem. I updated that and pew installed fine.

**Comment by ryanhiebert** [comment]
On the default install of python for OS X, the version of `setuptools` is 1.1.6. It's not easily possible to upgrade, because the file permissions have been changed to make it difficult, even using sudo. I'm actually wanting to do a `--user` install, but that's still just using the system `setuptools` of 1.1.6.

What would it take to allow it to work with older versions of `setuptools`? I know it's less than desirable, but I don't think that we should be requiring updating system libraries in order to use `pew`.

**Comment by berdario** [comment]
It wouldn't be difficult at all, but I just relied on that small little feature, assuming that upgrading (if needed) wouldn't be difficult.

I assume you're talking about System Integrity Protection? I read about it, but I had no idea this could impact us.

I'm thinking if it might be worth it to have 2 packages on pypi (either for pew or pythonz-bd):

a `pew` and `pew-legacy` if you wish (or rather: `pew-fancy` and `pew`)

and then, noting in the README:

> If you have an updated version of setuptools (or you can update it), install `pew` (or `pew-fancy`?), while if instead you're stuck with an old version of setuptools, install `pew-legacy` (or `pew`?)

The only reason I'd do this, is that I don't want to be too complacent with vendors that don't update the software they ships: it's fine to be compatible, but workarounds shouldn't stick forever, and making it clear to the users might be a way to put a bit of pressure into asking for a change.

I'll see to do it tomorrow, sorry again for the inconvenience

**Comment by ryanhiebert** [comment]
I'm not convinced it's worth having two packages. It's extra confusion. I get not wanting for workarounds to have to stick around, but I think with system libraries like this, it's somewhat unavoidable.

----------------

I'll let folks coming to look at this know how I finally installed the latest version of `pew`: I used `pipsi` (https://github.com/mitsuhiko/pipsi). It creates a separate virtualenv for each package that you install, and exposes the binaries. This is a great way to avoid system conflicts that can't be resolved by simply using `pip --user`.

**Comment by berdario** [comment]
I uploaded `pythonz-bd==1.11.1` so this issue should now be fixed... sorry for the delay!

(I also saw that there's another issue were people suggest to make pythonz optional... I'll have a look at it)

@ryanhiebert thanks for the hint about pipsi:
I'm still affected by problems like [this one](http://stackoverflow.com/a/27341847/293735). And I frankly blame Ubuntu/Debian for that: not only they ship an outdated pip, but the bug wouldn't appear if they retained the vendored libraries that pip ships exactly to avoid to problem (it's cleaner to avoid vendoring, but in that case they should be much more active in updating)

That happens because I sometimes still install stuff globally (like [electrum](https://electrum.org/)), but since the normal linux packages cannot quite be relied upon, now I moved to install similar stuff with pipsi... too bad that pipsi doesn't easily allow to upgrade packages and to enable/disable the global site packages...
