### ISSUE TITLE
inve blames the command path when cwd doesn't exist

### ISSUE THREAD

**Issue by christophebiocca** [berdario/pew#74]
If `kwargs['cwd']` doesn't exist (and thus OSError 2 is raised in `inve`), pew will say the shell doesn't exist.

You might want to just print the error instead.

**Comment by berdario** [comment]
That's weird... Are you trying to use pew as a library and the problem is that you're not supplying cwd? 

Cwd is not supplied either in the `shell` function. 

What is the exact error that you get?  What are the commands and the environment? 

Thank you

On 26 November 2015 17:57:34 GMT+00:00, Christophe Biocca <notifications@github.com> wrote:
>If `kwargs['cwd']` doesn't exist (and thus OSError 2 is raised in
>`inve`), pew will say the shell doesn't exist.
>
>You might want to just print the error instead.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/berdario/pew/issues/74

-- 
Sent from mobile. Please excuse my brevity.

**Comment by christophebiocca** [comment]
Sorry, I should have provided more context.

When setting up, I accidentally messed up the content of `~/.local/share/virtualenvs/myproject/.project` to point to an invalid path.

Then calling `pew workon myproject` I get `Unable to find /usr/bin/zsh` as an error message.

It's not a big deal, but it did send me on a wild goose chase for a bit.

The relevant code is https://github.com/berdario/pew/blob/master/pew/pew.py#L128

**Comment by berdario** [comment]
Yeah, it was a bit unexpected: it was an `OSError` with the exact same errno as when the program doesn't exist.

Sorry for taking so long  to fix it, and thanks for the report!
