### ISSUE TITLE
can't install when both 3.5 and 2.7.10 on os x

### ISSUE THREAD

**Issue by lewisl** [berdario/pew#79]
I am not very good at debugging broken installs and dependencies.

Here is what happens:
sudo -H pip install pew
Collecting pew
  Downloading pew-0.1.18-py2.py3-none-any.whl
Collecting pythonz-bd>=1.10.2 (from pew)
  Downloading pythonz-bd-1.10.2.tar.gz (85kB)
    100% |████████████████████████████████| 86kB 3.8MB/s 
    Complete output from command python setup.py egg_info:
    error in pythonz-bd setup command: Invalid environment marker: python_version>="3.5"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-VI9n4h/pythonz-bd

Some questions:
1. haven't wheels pretty much supplanted eggs?--I see that it is a wheel, so I don't understand the message that refers to python setup.py egg_info.
2. My system path points to Python 2.7.10 in /Library/Frameworks--NOT /System/Library/Frameworks.
3.  So, when I run pip I am installing against python 2.7.10 so why the error message about python_version="3.5".  You shouldn't be able to even see that Python 3.5 is there unless there is some error in your script--or, unlike virtualenvwrapper, you try to support all python's in parallel.

**Comment by art-solopov** [comment]
I have the same issue when installing pew on Ubuntu via pip.

**Comment by berdario** [comment]
Sorry, this was #71 

The solution was simply to upgrade setuptools, but on OsX this isn't simple at all, apparently
It has now been fixed.

Re. your first question:

> [pip can install from either Source Distributions (sdist) or Wheels, but if both are present on PyPI, pip will prefer a compatible wheel.](http://python-packaging-user-guide.readthedocs.org/en/latest/installing/#source-distributions-vs-wheels)

Unfortunately, I'm not sure what constitutes a "compatible wheel", but I assume this might entail `extra_require`s

So: a wheel was being used for `pew`, but `pythonz` was being installed through the source tarball probably because of the `extra_require`
