### ISSUE TITLE
cannot change into environment when using babun ( zsh running on windows)

### ISSUE THREAD

**Issue by timeyyy** [berdario/pew#80]
Installs and creates successfully using pip. 

However i receive this when it finishes creating the env

`The system cannot find the path specified.`

**Comment by timeyyy** [comment]
any pointers?

**Comment by ryanhiebert** [comment]
Perhaps a full log will give better insight. I'm not as familiar with zsh, but I'll see if a log gives me any clues.

**Comment by timeyyy** [comment]
pew logs? Where would i find a log?

**Comment by ryanhiebert** [comment]
Sorry, I just meant for you to run the command that is failing, and copy-paste the whole session so that I can see it.

**Comment by timeyyy** [comment]
> pew new test       
```zsh                                                                    ~
pew new tester                                                                         ~
Using base prefix 'c:\\python35'
New python executable in tester\Scripts\python.exe
Installing setuptools, pip, wheel...done.
The system cannot find the path specified.
```

>pew workon tester    
```zsh                                                
The system cannot find the path specified.
```

**Comment by ryanhiebert** [comment]
Blast. I was hoping it would tell me _which_ path it didn't find.

**Comment by berdario** [comment]
Uhm, that seems a Windows error message (due to CreateProcess).

(Again, I procrastinated dealing with the last few issues :/ I'll try to deal with this by the end of the week for real this time)

Thank you for the bug report! and sorry for the inconvenience

**Comment by timeyyy** [comment]
I can help out if you need, i couldn't find a `CreateProcess` function though

**Comment by berdario** [comment]
Ok, I felt really bad by neglecting these issues, and every time that I thought about it, that idea pushed me away from going back to work on pew once again :/

Now I finally booted into windows to dig into this issue.

Good news: pew has worked inside `babun` all along.

Bad news: this applies only to a python installed inside cygwin.

This is the [`CreateProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) I was talking about. Python's [subprocess](https://docs.python.org/3/library/subprocess.html) uses `popen` on posix systems, and `CreateProcess` on windows. So what I meant earlier is that the error was due to a `subprocess.call` or `subprocess.check_call`, and the error message was Windows specific.

Basically, the problem you've found is because `SHELL` is set to `/bin/zsh`, but `CreateProcess` is unable to find `/bin/zsh` (obviously, since that's not a valid Windows path)

You can work around it with `env SHELL=zsh pew workon envname` or `pew in envname zsh`

But then you'll stumble another error... pew will use `sys.executable` (that is the path of the Python interpreter itself). The problem now is the opposite: this is a Windows path and it'll be supplied as an argument to `SHELL` (zsh in this case) which doesn't treat `\` as the file separator.

I tried to make a simple conversion with `Path(sys.executable).as_posix()` but this will yield `C:/yada/yada` which won't still be accepted by zsh due to the leading drive specifier.

You can see the difference in behavior between the 2 pythons here:

    { ~ }  » /usr/bin/python                                                                        ~
    Python 2.7.8 (default, Jul 28 2014, 01:34:03)
    [GCC 4.8.3] on cygwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.path.sep
    '/'
    >>> from subprocess import call
    >>> call(['/bin/zsh', '-c', 'echo 1'])
    1
    0
    >>> exit()
    [1]    6228 abort (core dumped)  /usr/bin/python
    { ~ }  » /cygdrive/c/tools/python2/python -i                                                ~ 134
    Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import os
    >>> os.path.sep
    '\\'
    >>> from subprocess import call
    >>> call(['/bin/zsh'])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\tools\python2\lib\subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "C:\tools\python2\lib\subprocess.py", line 710, in __init__
        errread, errwrite)
      File "C:\tools\python2\lib\subprocess.py", line 958, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified
    

Maybe that could be fixed with something like [what mingw is doing](http://www.mingw.org/wiki/Posix_path_conversion). Furthermore, I think that if you don't actually need the whole Posix API, but you only want an unix-like shell, mingw is a simpler solution.

Another solution could be to change the way the the shell_check is done, but I don't like the idea of making more code that is shell-specific. At the same time, I don't feel like adding kludges to fix this, guessing the correct format for the path that we're dealing with, etc.

Especially when pew is already working correctly on a normal Windows environment and a Python installed on that environment, and on a Posix environment and a Python installed on that environment.

So, what you might want to do is install pew inside cygwin. Urllib3 complains about the TLS certificates stuff on Python2.7.8.
Since cygwin only currently ships that old (and [insecure](https://www.python.org/dev/peps/pep-0466/)) version of Python2, you might want to install Python3. You also need pip (actually, just an updated setuptools) at least until I won't have relaxed the setuptools requirement in `pythonz-bd`

    pact install python3-setuptools
    /usr/bin/easy_install-3.4 pip
    /usr/bin/pip3 install pew

and voila (you might need to `rebaseall` your cygwin, if you'll stumble on some [`address space needed by 'whatever.dll' (0x960000) is already occupied` error](http://stackoverflow.com/questions/11107155/how-to-fix-address-space-is-already-occupied-error-on-fetch-commit))


I'll leave this issue open for now, in case there'll be another idea... otherwise I'll just document these steps for installing pew inside cygwin.

**Comment by timeyyy** [comment]
Ill try installing pew in babun and report if I have any difficultie. if all goes well we can close this and ill make a pull request for the troubleshooting section

**Comment by berdario** [comment]
Hi @timeyyy 

did you get it to work inside babun?

I now updated the README, but if there's something else that can be fixed, please tell me

**Comment by timeyyy** [comment]
We got a step futher, but i guess i have to setup some more stuff

```
New python executable in /cygdrive/c/Users/timeyyy/.local/share/virtualenvs/test/bin/python2.7
Not overwriting existing python script /cygdrive/c/Users/timeyyy/.local/share/virtualenvs/test/bin/python (you must use /cygdrive/c/Users/timeyyy/.local/share/virtualenvs/test/bin/python2.7)
Installing setuptools, pip, wheel...done.
ERROR: The virtualenv hasn't been activated correctly.
Either the env is corrupted (try running `pew restore env`),
Or an upgrade of your Python version broke your env,
Or check the contents of your $PATH. You might be adding new directories to it
from inside your shell's configuration file.
```
In this case, for further details please see: https://github.com/berdario/pew#the-environment-doesnt-seem-to-be-activated

**Comment by berdario** [comment]
Uhm, I see that you're using python2 (apparently the cygwin guys are now shipping an updated version: 2.7.10, which is good)

I wonder if the second error you got might be due to an incompatibility with cygwin of the backported `pathlib`.

I tried to run the restore command, and I don't get that error, even with a non-existing env, it'll try to readlink `/home/Dario/.local/share/virtualenvs/test` as expected.

A path that ends in `/C:` seems definitely suspicious. Do you get the same error if you install pew on Python3?

Unfortunately, I never use cygwin... I rebooted into windows just to try this out, ohmyzsh got updated, but now almost nothing works:

both pip and virtualenv fail due to stuff like `resource temporarily unavailable` while forking, and the problem persists even after running `rebaseall`, so trying to debug issues on cygwin is impossible for me

**Comment by timeyyy** [comment]
are you saying its a path setting? 

python3 wasn't much better
```
Traceback (most recent call last):
  File "/usr/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/usr/lib/python3.4/site-packages/pew/pew.py", line 685, in pew
    return command(sys.argv[2:])
  File "/usr/lib/python3.4/site-packages/pew/pew.py", line 321, in workon_cmd
    shell(env, cwd=project_dir)
  File "/usr/lib/python3.4/site-packages/pew/pew.py", line 171, in shell
    inve(env, shell, '-c', shell_check)
  File "/usr/lib/python3.4/site-packages/pew/pew.py", line 128, in inve
    return check_call([command] + list(args), shell=windows, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```
