### ISSUE TITLE
No such file or directory: 'virtualenv' when using Python3.4

### ISSUE THREAD

**Issue by Lucas-C** [berdario/pew#88]
Reproduction steps, under Cygwin :
```
$ pip3.4 install --user pew

$ pew new offerscatalog -p python3.4
Traceback (most recent call last):
  File "/home/lucas_cimon/.local/bin/pew", line 11, in <module>
    sys.exit(pew())
  File "/home/lucas_cimon/.local/lib/python3.4/site-packages/pew/pew.py", line 684, in pew
    return command(sys.argv[2:])
  File "/home/lucas_cimon/.local/lib/python3.4/site-packages/pew/pew.py", line 225, in new_cmd
    args.requirements, rest)
  File "/home/lucas_cimon/.local/lib/python3.4/site-packages/pew/pew.py", line 184, in mkvirtualenv
    check_call(["virtualenv", envname] + rest, cwd=str(workon_home))
  File "/usr/lib/python3.4/subprocess.py", line 556, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv'

$ type virtualenv
virtualenv is /home/lucas_cimon/.local/bin/virtualenv
```

Despite the `virtualenv` command being in my $PATH, it seems that the `check_call` invocation fails here : https://github.com/berdario/pew/blob/master/pew/pew.py#L184

**Comment by Lucas-C** [comment]
Note that if I replace the string `virtualenv` on line 184 by the full command path, it all works fine.

Btw: is there a check somewhere that this `virtualenv` command matches the Python version picked ? Wouldn't `python -m virtualenv` be a better alternative ?

**Comment by Lucas-C** [comment]
OK, sorry, my bad: I had removed the directory containing the `virtualenv` command from my `$PATH` before invoking `pew`, hence the problem.
Closing this now

**Comment by berdario** [comment]
> Btw: is there a check somewhere that this virtualenv command matches the Python version picked ? Wouldn't python -m virtualenv be a better alternative ?

Indeed, it's a bit of a shame, but it's not checked. The ideal would be to directly import virtualenv it to avoid forking a separate process, but this is pointless and impossible since [here](https://github.com/pypa/virtualenv/blob/ac4ea65/virtualenv.py#L665) it'd fork the existing process itself again

That said, virtualenv isn't used in a special way at all, so any version would be fine... the only important thing would be for it to have the relevant patches/fixes for the Python version required by the user  (in case there were issues with e.g. Python3.3 or pypy).
