### ISSUE TITLE
Make pythonz-bd optional

### ISSUE THREAD

**Issue by jlesquembre** [berdario/pew#89]
Move this dependency to extras_require, and show an error message to the user if he tries to install a new python version, but pythonz is not installed. This change would make the linux packages more user-friendly. 

e.g. for the archlinux package, since the package is not in the official repositories, when you try to generate the package, you get an error because the package depends on pythonz-bd. So you need to install pythonz-bd before, but then you get a new error, because pythonz-db depends on resumable-urlretrieve. The main problem  with the linux packages, is that for every dependency you add on your python package, you need to generate a new linux package, so it would be easier for the packagers to keep the mandatory dependencies to the minimum.

**Comment by berdario** [comment]
Uhm, I understood this issue to mostly be:

> it would be easier for the packagers to keep the mandatory dependencies to the minimum

(btw, thanks again for your work on keeping the arch package up to date!)

Rather than removing features, I'd like to help with the packaging effort, so I dusted off my Arch VM (gosh, I haven't used it since June 2011, and it was a pain to update :/ ) and I was ready to contribute a small PKGBUILD for resumable_urlretrieve

But then I realized that it has already been pushed to AUR... I then installed [aura](https://github.com/aurapm/aura) and used it to install `python-pew`

And everything works quite smoothly.

Also, while Arch is quite bleeding edge, and thus pythonz won't be used to install e.g. Python 3.5.1 ...apparently older versions aren't available in the main repositories (I'm sure they might be on AUR, though), and thus pythonz is still useful. (if pythonz had no use case on Arch, removing it might have been more acceptable)

So, I'm not quite sure about the problem you mentioned:

> for the archlinux package, since the package is not in the official repositories, when you try to generate the package, you get an error because the package depends on pythonz-bd. So you need to install pythonz-bd before, but then you get a new error, because pythonz-db depends on resumable-urlretrieve.

I mean: python-pew is not in the official repositories either, and thus the same tool that installs pew should be able to fetch pythonz and resumable_urlretrieve (and that's the case in my experience)

If you plan for them to be moved as extra dependencies, and then specify them as extra dependencies for Arch, this wouldn't really be any easier for you, am I right? And since afaik (maybe it changed in the last version) pip doesn't prominently tell you about optional dependencies, and that the syntax for installing optional stuff is not well known (`pip install package[option]`)... I feel like making this optional would simply make features disappear for the less savvy users (also, what happend when you `pip install --upgrade` the package? does it also upgrades the optional dependencies? if not this might lead to broken packages... I'd need to look into this)

Obviously I could try to educate users, and add an appropriate message (like "run pip install pythonz-bd, but only if you installed pew via pip") when the users invokes `pew install`

But if the issue is only the maintenance workload for the Arch (and potentially other distros) packager, I promise you that `resumable_urlretrieve` won't receive a lot of updates: it only needs to do 1 thing, and it's arguably better tested than `pew`. And for the couple of pythonz features used by pew, we don't need to really keep it up to date. Most updates are for the newer python versions, but pythonz is able to install them even without (it just won't list them as available and won't be able to check their sha256).

So, for me it'd be perfectly fine if the Arch pythonz-bd and resumable-urlretrieve packages will be lagging behind a bit

**Comment by jlesquembre** [comment]
The main issue here is that I'm installing AUR packages manually, I didn't know about aura, but I don't want to use such tools because I want to control which packages from the AUR are installed on my system. The way the standard archlinux utilities work, I can create the `python-pew` package, but when I try to install it, I get an error about the dependency `python-pythonz-db`, so I need to generate and install that package, but I get again the same error about `python-resumable-urlretrieve`. That's because you cannot handle automatically dependencies from the AUR with the official Archlinux tools. Anyways, you are right about the problems the users will have if they handle `pew` directly with `pip`. 

This issue is probably too arch specific, and it will be completely solve if some day `pew` is included in the official repositories . Thinking again about it, I regret to write this issue, you can close it. As far as you keep using `pythonz` inside `pew`, makes totally sense to have it on the dependencies. Sorry for the problems caused to you for updating your Arch VM. Also, maintaining the Arch packages is a relatively easy task, specially with the help from [Arthru](https://aur.archlinux.org/account/arthru)

Thanks for your reply (and for `pew` :-) ), I'm closing this issue.
