### ISSUE TITLE
No history in python3 inside the virtualenv

### ISSUE THREAD

**Issue by Phyks** [berdario/pew#90]
Hi,

Not sure if this issue is pew-specific or not, but I could not find much information on it… Inside a virtualenv (`pew workon venv`), I do not have history across different calls of Python.

Is it expected? Is there a way to recover an history?

Thanks!

**Comment by berdario** [comment]
This is a [known Virtualenv bug](https://github.com/pypa/virtualenv/issues/355)

I already noticed it before, but I didn't dig to the root cause.

The only solution is a [rewrite of virtualenv](https://github.com/pypa/virtualenv/pull/697)

I think that adapting [virtualenv-rewrite](https://pypi.python.org/pypi/virtualenv-rewrite) might work.

**Comment by Phyks** [comment]
Ok, will follow this issue. Thanks!

**Comment by Lucas-C** [comment]
As a workaround, here is my `.pythonrc` (loaded thanks to `export PYTHONSTARTUP=~/.pythonrc`) :
```
import atexit, os, readline, sys
if sys.version_info >= (3, 0) and hasattr(sys, 'real_prefix'): # in a VirtualEnv
    PYTHON_HISTORY_FILE = os.path.join(os.environ['HOME'], '.python_history')
    if os.path.exists(PYTHON_HISTORY_FILE):
        readline.read_history_file(PYTHON_HISTORY_FILE)
        atexit.register(readline.write_history_file, PYTHON_HISTORY_FILE)
```
