### ISSUE TITLE
python 3.5 without ssl v2

### ISSUE THREAD

**Issue by JPFrancoia** [berdario/pew#93]
Hi,

I just have a quick question. Is it possible to install a specific version of python, but with ssl v2 disabled, in a pew environment ?

I'm on Manjaro Linux, and it seems python is built with sslv2. So when I package my softwares, and use them on Ubuntu for example, I encounter some problems.

Thanks !

**Comment by berdario** [comment]
I think I'd need more details to understand exactly what you need (also, I'm not at my computer)

Pew environments are just normal virtualenvs. You can use the same command line flags and those will be passed through to virtualenv, like `--python`

So, if you have a Python like that, you can simply supply it like that...

If what you're asking is an option for the "pew install" command, then this'd be a feature request for pythonz

Tls support is defined in the ssl module and by the version of openssl linked. I'm not sure how you can customize it, but you could probably do it in a PYTHONSTARTUP

But that might not be what you want, since you're talking about packaging... 

You're talking about packaging it and running on Ubuntu, so I guess that you're using Manjaro to create to some debs? 
-- 
Sent from mobile. Please excuse my brevity.

**Comment by JPFrancoia** [comment]
Ok. On Manjaro Linux, it seems python is built with ssl version 2 enabled. So the file:

```
/usr/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so
```

Somewhere contains the symbol:
```
SSLv2_method
```

When I package my software (let's say with cx_Freeze for example, to easily distribute my software to end-users), this file is included in the bundle. And when I try to run the package on a fresh install of Ubuntu, I get the error:

```
ImportError: /home/ubuntu/Desktop/ChemBrows-0.9.6.linux-x86_64/ChemBrows-0.9.6.linux-x86_64/_ssl.cpython-35m-x86_64-linux-gnu.so: undefined symbol: SSLv2_method
```

I patched openssl on Ubuntu, to enable SSLV2. And now my package is runnable. However, if I was able to do it, I can't ask my users to patch a system library.
I think if I build my package, on Manjaro, with sslV2 disabled, I won't have this problem on Ubuntu.

So, here is my question: can I build python, in a pew environment (to not mess with my system), with sslV2 disabled ?

**Comment by JPFrancoia** [comment]
So, any idea ? I know it's really a pew issue, but it could save my life.

**Comment by berdario** [comment]
If you run `ldd` on your `_ssl.foo.so`, you'll probably see something like this:

```
ldd /home/dario/.pythonz/pythons/CPython-3.5.0/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffca35f5000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f5a893e2000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f5a88f87000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5a88d69000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a889a0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a8879c000)
	/lib64/ld-linux-x86-64.so.2 (0x000056046126d000)
```

This means that libssl is dynamically linked to `/lib/x86_64-linux-gnu/libssl.so.1.0.0` (as you might've expected, since the .so was in a `lib-dynload` folder)... what you want to do is probably to statically link openssl in your python, and then select that python with `--python`  (enabling SSL2 is also a bad idea, but you're probably interacting with a really legacy server and don't have much alternatives)

Whenever I have to deal with non-python dependencies, I find [Nixos](https://nixos.org/wiki/Development_Environments#Nixos_Container_Example:_Python_Web_Development) the best solution for such problems (but then to deploy it to the users, if they're not running Nix, you'd need to ship the whole `/nix/store` or maybe to create a container for it)


Sorry for not replying earlier
